version: '3'
services:
  client:
    container_name: wg_client
    restart: always
    build: apps/client
    ports:
      - 3000:3000
    depends_on:
      - server

  server:
    container_name: wg_server
    restart: always
    build: apps/server
    ports:
      - 4000:4000
